---
title: "PLSC 40601 --- Final Project Proposal"
author: "Robert Winter"
format: pdf
editor: visual

highlight-style: pygments
geometry:
      - top=30mm
      - left=30mm
#toc: true
#toc-title: Table of Contents
# number-sections: true

echo: false
warning: false
output: false

# Wrap code chunk text
include-in-header:
  text: |
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    
bibliography: references.bib
link-citations: true
---

To motivate their examination of causal forests, Wager and Athey write that "classical approaches to nonparametric estimation of heterogeneous treatment effects" like "nearest neighbor matching... perform well in applications with a small number of covariates, but quickly break down as the number of covariates increases" [@wager2018]. Wager and Athey go on to "compare the performance of \[their\] causal forest algorithm against classical $k$-nearest neighbor matching using simulations, finding that the causal forest dominates in terms of both bias and variance in a variety of settings, and that its advantage increases with the number of covariates" [@wager2018].

Nevertheless, since Wager and Athey's publiation, several researchers have continued to investigate the use of KNN for causal inference [@hitsch; @kricke; @zhou]. In my Tutorial Project, I am interested in reviewing how KNN approaches for causal inference have improved since Wager and Athey's 2018 publication, and whether there are situations in which a KNN approach might actually be preferable to an adaptive nearest neighbors method like causal forests.

# References
